### ISSUE TITLE
May i know the difference between the QII and Shapley values?

### ISSUE THREAD

**Issue by man0007** [hovinh/QII#3]
As we know that QII is quantitative input influence and similarly the shapley values state the same too, that is, the fair distribution of the gains and costs for each feature involved in decision making. So what is the difference between QII and shapley values then, are these both the same?

**Comment by hovinh** [comment]
I would assume you are not meant to compare SHAP with QII, which could be found in great details <a href="https://papers.nips.cc/paper/2017/file/8a20a8621978632d76c43dfd28b67767-Paper.pdf">here</a>.

To my understanding, in the context of game theory, Shapley value refers to a **sampling approach** over permutation set to approximate the contribution of each agent i in the set of agents N. This can work assume you have a function f(.) that given a set of agents S \in N, one can know their reward/utility.

I would say QII is an adapted version of Shapley value in the Interpretable Machine Learning field. It does that by defining a way to encode the absence of feature (agent) i in an input and the utility function f(.):
- Feature absence encoding: Instead of creating a new interpretable feature space as in LIME, QII can do directly on the original feature. They reason that the missing of a variable is equivalent to the average prediction of all possible values that that variable can take. For example, assume your input has two variables x_1 and x_2, each can have {1, 2, 3} as possible values. To compute how an ML model behaves with x_1 absent, it's equivalent to the average outcome of f(x_1=1, x_2), f(x_1=2, x_2), and f(x_1=3, x_2) combine.
- Utility function: QII let you determine this function using the quantity of interest. Normally the predicted probability of the class of interest (cat/no cat in a cat classifier for example) is used, but not limited to. For this second point, due to its flexibility, I would say this is an extension.

Hope this helps.
